name: floaty_nav_bar
description: "A Flutter package that provides a floating navigation bar that provide a custom floating button for each tab."
version: 0.0.1
homepage: https://github.com/Mustafa7Ibrahim/floaty_nav_bar

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

